import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#00443e",
        "tertiary-fixed-dim": "#6bd8cb",
        "outline-variant": "#bec9c2",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#1d3989",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#3f4944",
        "secondary-fixed": "#dce1ff",
        "surface": "#f7f9fb",
        "secondary": "#4059aa",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#264191",
        "outline": "#6f7973",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#065f46",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#89f5e7",
        "on-primary-fixed-variant": "#00513b",
        "tertiary-container": "#005e56",
        "inverse-primary": "#8bd6b6",
        "primary": "#004532",
        "on-background": "#191c1e",
        "on-primary-fixed": "#002116",
        "on-tertiary-container": "#6cd9cb",
        "primary-fixed": "#a6f2d1",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#b6c4ff",
        "secondary-container": "#8fa7fe",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#00164e",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed-variant": "#005049",
        "surface-tint": "#1b6b51",
        "on-primary-container": "#8bd6b7",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#00201d",
        "primary-fixed-dim": "#8bd6b6",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "margin-tablet": "2rem",
        "space-3xl": "4rem",
        "max-content-width": "1280px",
        "space-2xl": "3rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "margin-desktop": "3rem"
      },
      fontFamily: {
        "headline-md": [ "Plus Jakarta Sans", "Sarabun", "sans-serif" ],
        "body-md": [ "Inter", "Sarabun", "sans-serif" ],
        "body-lg": [ "Inter", "Sarabun", "sans-serif" ],
        "title-lg": [ "Inter", "Sarabun", "sans-serif" ],
        "display-lg-mobile": [ "Plus Jakarta Sans", "Sarabun", "sans-serif" ],
        "display-lg": [ "Plus Jakarta Sans", "Sarabun", "sans-serif" ],
        "headline-lg": [ "Plus Jakarta Sans", "Sarabun", "sans-serif" ],
        "label-md": [ "Inter", "Sarabun", "sans-serif" ],
        "label-lg": [ "Inter", "Sarabun", "sans-serif" ],
        "code-md": [ "JetBrains Mono", "monospace" ],
        "headline-sm": [ "Plus Jakarta Sans", "Sarabun", "sans-serif" ],
        "body-sm": [ "Inter", "Sarabun", "sans-serif" ],
        "label-sm": [ "Inter", "Sarabun", "sans-serif" ]
      },
      fontSize: {
        "headline-md": [ "22px", { "lineHeight": "28px", "fontWeight": "600" } ],
        "body-md": [ "14px", { "lineHeight": "20px", "fontWeight": "400" } ],
        "body-lg": [ "16px", { "lineHeight": "24px", "fontWeight": "400" } ],
        "title-lg": [ "16px", { "lineHeight": "22px", "fontWeight": "600" } ],
        "display-lg-mobile": [ "30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "display-lg": [ "40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" } ],
        "headline-lg": [ "28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" } ],
        "label-md": [ "12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" } ],
        "label-lg": [ "14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" } ],
        "code-md": [ "13px", { "lineHeight": "18px", "fontWeight": "500" } ],
        "headline-sm": [ "18px", { "lineHeight": "24px", "fontWeight": "600" } ],
        "body-sm": [ "12px", { "lineHeight": "16px", "fontWeight": "400" } ],
        "label-sm": [ "11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" } ]
      }
    },
  },
  plugins: [],
};
export default config;
